import { Role, Status } from '../models/Employee';
import { LeaveStatus, LeaveType } from '../models/Leave';
import { AttendanceStatus } from '../models/Attendance';
import { PayrollStatus } from '../models/Payroll';
import { NotificationType } from '../models/Notification';
import { AuditAction } from '../models/AuditLog';

export const DEFAULT_PASSWORD = 'Password123!';
export const ADMIN_PASSWORD = 'Admin@123';

export const DEPARTMENTS = [
  { name: 'Engineering', description: 'Product development and platform engineering' },
  { name: 'Human Resources', description: 'People operations, hiring, and culture' },
  { name: 'Sales', description: 'Revenue growth and client relationships' },
  { name: 'Marketing', description: 'Brand, campaigns, and demand generation' },
  { name: 'Finance', description: 'Accounting, payroll, and financial planning' },
];

export interface SeedEmployeeDef {
  key: string;
  employeeId: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  department: string;
  designation: string;
  salary: number;
  role: Role;
  status: Status;
  managerKey?: string;
  joiningDate: string; // YYYY-MM-DD
  profileImage?: string;
}

function avatar(name: string, bg: string) {
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=fff&size=128`;
}

export const EMPLOYEES: SeedEmployeeDef[] = [
  {
    key: 'admin',
    employeeId: 'EMP001',
    firstName: 'Rajesh',
    lastName: 'Sharma',
    email: 'admin@company.com',
    phone: '9876543210',
    department: 'Human Resources',
    designation: 'Chief Executive Officer',
    salary: 2500000,
    role: Role.SUPER_ADMIN,
    status: Status.ACTIVE,
    joiningDate: '2020-01-15',
    profileImage: avatar('Rajesh Sharma', '1e40af'),
  },
  {
    key: 'hr',
    employeeId: 'EMP002',
    firstName: 'Priya',
    lastName: 'Patel',
    email: 'hr@company.com',
    phone: '9876543211',
    department: 'Human Resources',
    designation: 'HR Manager',
    salary: 1200000,
    role: Role.HR_MANAGER,
    status: Status.ACTIVE,
    managerKey: 'admin',
    joiningDate: '2021-03-10',
    profileImage: avatar('Priya Patel', '7c3aed'),
  },
  {
    key: 'eng_head',
    employeeId: 'EMP003',
    firstName: 'Arjun',
    lastName: 'Mehta',
    email: 'arjun.mehta@company.com',
    phone: '9876543212',
    department: 'Engineering',
    designation: 'Engineering Director',
    salary: 1800000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'admin',
    joiningDate: '2021-06-01',
    profileImage: avatar('Arjun Mehta', '059669'),
  },
  {
    key: 'sales_head',
    employeeId: 'EMP004',
    firstName: 'Neha',
    lastName: 'Gupta',
    email: 'neha.gupta@company.com',
    phone: '9876543213',
    department: 'Sales',
    designation: 'Sales Director',
    salary: 1600000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'admin',
    joiningDate: '2021-08-20',
    profileImage: avatar('Neha Gupta', 'dc2626'),
  },
  {
    key: 'marketing_head',
    employeeId: 'EMP005',
    firstName: 'Vikram',
    lastName: 'Singh',
    email: 'vikram.singh@company.com',
    phone: '9876543214',
    department: 'Marketing',
    designation: 'Marketing Head',
    salary: 1400000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'admin',
    joiningDate: '2022-01-05',
    profileImage: avatar('Vikram Singh', 'ea580c'),
  },
  {
    key: 'finance_head',
    employeeId: 'EMP006',
    firstName: 'Anita',
    lastName: 'Desai',
    email: 'anita.desai@company.com',
    phone: '9876543215',
    department: 'Finance',
    designation: 'Finance Manager',
    salary: 1500000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'admin',
    joiningDate: '2022-02-14',
    profileImage: avatar('Anita Desai', '0891b2'),
  },
  {
    key: 'senior_dev_1',
    employeeId: 'EMP007',
    firstName: 'Rohan',
    lastName: 'Kapoor',
    email: 'rohan.kapoor@company.com',
    phone: '9876543216',
    department: 'Engineering',
    designation: 'Senior Software Engineer',
    salary: 1100000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'eng_head',
    joiningDate: '2022-05-18',
    profileImage: avatar('Rohan Kapoor', '2563eb'),
  },
  {
    key: 'senior_dev_2',
    employeeId: 'EMP008',
    firstName: 'Kavya',
    lastName: 'Iyer',
    email: 'kavya.iyer@company.com',
    phone: '9876543217',
    department: 'Engineering',
    designation: 'Senior Software Engineer',
    salary: 1050000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'eng_head',
    joiningDate: '2022-07-22',
    profileImage: avatar('Kavya Iyer', '4f46e5'),
  },
  {
    key: 'junior_dev',
    employeeId: 'EMP009',
    firstName: 'Amit',
    lastName: 'Verma',
    email: 'amit.verma@company.com',
    phone: '9876543218',
    department: 'Engineering',
    designation: 'Software Engineer',
    salary: 750000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'eng_head',
    joiningDate: '2024-11-01',
    profileImage: avatar('Amit Verma', '6366f1'),
  },
  {
    key: 'sales_rep_1',
    employeeId: 'EMP010',
    firstName: 'Sneha',
    lastName: 'Reddy',
    email: 'sneha.reddy@company.com',
    phone: '9876543219',
    department: 'Sales',
    designation: 'Account Executive',
    salary: 900000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'sales_head',
    joiningDate: '2023-04-12',
    profileImage: avatar('Sneha Reddy', 'be123c'),
  },
  {
    key: 'sales_rep_2',
    employeeId: 'EMP011',
    firstName: 'Karan',
    lastName: 'Malhotra',
    email: 'karan.malhotra@company.com',
    phone: '9876543220',
    department: 'Sales',
    designation: 'Sales Associate',
    salary: 650000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'sales_head',
    joiningDate: '2024-12-15',
    profileImage: avatar('Karan Malhotra', 'e11d48'),
  },
  {
    key: 'marketing_specialist',
    employeeId: 'EMP012',
    firstName: 'Divya',
    lastName: 'Nair',
    email: 'divya.nair@company.com',
    phone: '9876543221',
    department: 'Marketing',
    designation: 'Marketing Specialist',
    salary: 700000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'marketing_head',
    joiningDate: '2023-09-01',
    profileImage: avatar('Divya Nair', 'f97316'),
  },
  {
    key: 'accountant',
    employeeId: 'EMP013',
    firstName: 'Suresh',
    lastName: 'Pillai',
    email: 'suresh.pillai@company.com',
    phone: '9876543222',
    department: 'Finance',
    designation: 'Senior Accountant',
    salary: 850000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'finance_head',
    joiningDate: '2023-01-20',
    profileImage: avatar('Suresh Pillai', '0284c7'),
  },
  {
    key: 'hr_exec',
    employeeId: 'EMP014',
    firstName: 'Meera',
    lastName: 'Joshi',
    email: 'meera.joshi@company.com',
    phone: '9876543223',
    department: 'Human Resources',
    designation: 'HR Executive',
    salary: 600000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'hr',
    joiningDate: '2024-06-10',
    profileImage: avatar('Meera Joshi', '9333ea'),
  },
  {
    key: 'qa_engineer',
    employeeId: 'EMP015',
    firstName: 'Nikhil',
    lastName: 'Bansal',
    email: 'nikhil.bansal@company.com',
    phone: '9876543224',
    department: 'Engineering',
    designation: 'QA Engineer',
    salary: 720000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'eng_head',
    joiningDate: '2025-01-08',
    profileImage: avatar('Nikhil Bansal', '0d9488'),
  },
  {
    key: 'inactive_employee',
    employeeId: 'EMP016',
    firstName: 'Rahul',
    lastName: 'Chopra',
    email: 'rahul.chopra@company.com',
    phone: '9876543225',
    department: 'Sales',
    designation: 'Former Sales Rep',
    salary: 0,
    role: Role.EMPLOYEE,
    status: Status.INACTIVE,
    managerKey: 'sales_head',
    joiningDate: '2022-11-30',
    profileImage: avatar('Rahul Chopra', '6b7280'),
  },
  {
    key: 'intern',
    employeeId: 'EMP017',
    firstName: 'Isha',
    lastName: 'Khanna',
    email: 'isha.khanna@company.com',
    phone: '9876543226',
    department: 'Engineering',
    designation: 'Engineering Intern',
    salary: 300000,
    role: Role.EMPLOYEE,
    status: Status.ACTIVE,
    managerKey: 'senior_dev_1',
    joiningDate: '2025-02-01',
    profileImage: avatar('Isha Khanna', '8b5cf6'),
  },
];

export const LEAVE_SEEDS = [
  {
    employeeKey: 'junior_dev',
    leaveType: LeaveType.SICK,
    startOffsetDays: -2,
    endOffsetDays: -1,
    reason: 'Flu and fever — doctor advised rest',
    status: LeaveStatus.PENDING,
  },
  {
    employeeKey: 'sales_rep_1',
    leaveType: LeaveType.CASUAL,
    startOffsetDays: 3,
    endOffsetDays: 4,
    reason: 'Family function out of town',
    status: LeaveStatus.PENDING,
  },
  {
    employeeKey: 'marketing_specialist',
    leaveType: LeaveType.EARNED,
    startOffsetDays: -14,
    endOffsetDays: -12,
    reason: 'Short vacation',
    status: LeaveStatus.APPROVED,
    reviewerKey: 'hr',
  },
  {
    employeeKey: 'accountant',
    leaveType: LeaveType.UNPAID,
    startOffsetDays: -20,
    endOffsetDays: -18,
    reason: 'Personal emergency',
    status: LeaveStatus.APPROVED,
    reviewerKey: 'hr',
  },
  {
    employeeKey: 'senior_dev_2',
    leaveType: LeaveType.CASUAL,
    startOffsetDays: -7,
    endOffsetDays: -7,
    reason: 'Appointment',
    status: LeaveStatus.REJECTED,
    reviewerKey: 'hr',
    reviewNote: 'Critical release week — please reschedule',
  },
  {
    employeeKey: 'hr_exec',
    leaveType: LeaveType.SICK,
    startOffsetDays: -5,
    endOffsetDays: -4,
    reason: 'Migraine',
    status: LeaveStatus.APPROVED,
    reviewerKey: 'hr',
  },
];

export const MESSAGE_SEEDS = [
  {
    senderKey: 'hr',
    recipientKey: 'junior_dev',
    subject: 'Welcome to the Engineering Team',
    content: 'Hi Amit, welcome aboard! Your onboarding checklist is ready. Let me know if you need anything.',
    isRead: true,
  },
  {
    senderKey: 'eng_head',
    recipientKey: 'senior_dev_1',
    subject: 'Sprint Planning — Q2 Roadmap',
    content: 'Please review the attached sprint goals before our Monday standup. Focus on the auth module refactor.',
    isRead: false,
  },
  {
    senderKey: 'sales_head',
    recipientKey: 'sales_rep_1',
    subject: 'Q1 Targets Update',
    content: 'Great work closing the Acme deal! You are at 85% of your quarterly target. Keep it up.',
    isRead: true,
  },
  {
    senderKey: 'admin',
    recipientKey: 'hr',
    subject: 'All-Hands Meeting Next Week',
    content: 'Please schedule the company all-hands for next Thursday. Include department highlights.',
    isRead: false,
  },
  {
    senderKey: 'finance_head',
    recipientKey: 'accountant',
    subject: 'March Payroll Review',
    content: 'March payroll drafts are ready for your review. Two unpaid leave deductions need verification.',
    isRead: false,
  },
];

export const NOTIFICATION_SEEDS = [
  {
    recipientKey: 'hr',
    title: 'New Leave Request',
    message: 'Amit Verma applied for Sick leave (2 days)',
    type: NotificationType.LEAVE,
    link: '/leaves',
    isRead: false,
  },
  {
    recipientKey: 'hr',
    title: 'New Leave Request',
    message: 'Sneha Reddy applied for Casual leave (2 days)',
    type: NotificationType.LEAVE,
    link: '/leaves',
    isRead: false,
  },
  {
    recipientKey: 'senior_dev_1',
    title: 'New Message',
    message: 'Arjun Mehta sent you: Sprint Planning — Q2 Roadmap',
    type: NotificationType.MESSAGE,
    link: '/messages',
    isRead: false,
  },
  {
    recipientKey: 'admin',
    title: 'System Update',
    message: 'Employee Management System demo data loaded successfully.',
    type: NotificationType.SYSTEM,
    isRead: true,
  },
  {
    recipientKey: 'junior_dev',
    title: 'Welcome!',
    message: 'Your profile has been set up. Explore attendance, leaves, and messages.',
    type: NotificationType.SYSTEM,
    isRead: false,
  },
];

export { AttendanceStatus, PayrollStatus, AuditAction };
